// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 是暴露给前端的聊天服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteSession 删除会话。
 */
export function DeleteSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3245855500, sessionID);
}

/**
 * GetMessages 返回会话内全部消息。
 */
export function GetMessages(sessionID: string): $CancellablePromise<$models.MessageDTO[] | null> {
    return $Call.ByID(1299761005, sessionID);
}

/**
 * GetSessions 返回全部会话（按最近更新倒序）。
 */
export function GetSessions(): $CancellablePromise<$models.SessionDTO[] | null> {
    return $Call.ByID(1104449860);
}

/**
 * GetSettings 返回当前设置副本。
 */
export function GetSettings(): $CancellablePromise<config$0.Settings | null> {
    return $Call.ByID(1831475952);
}

/**
 * ListModels 扫描 OpenAI-compatible 端点的可用模型（用于设置页下拉）。
 */
export function ListModels(baseURL: string, apiKey: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(1421602273, baseURL, apiKey);
}

/**
 * NewSession 新建一个空会话。
 */
export function NewSession(): $CancellablePromise<$models.SessionDTO | null> {
    return $Call.ByID(787229693);
}

/**
 * SaveSettings 校验并保存设置。
 */
export function SaveSettings(st: config$0.Settings | null): $CancellablePromise<void> {
    return $Call.ByID(2063764331, st);
}

/**
 * SendMessage 把用户消息追加到会话并异步流式请求模型。
 * effort 取值 ""|"low"|"medium"|"high"，作为 reasoning_effort 透传。
 * 返回错误表示同步失败（会话不存在 / 正忙 / 未配置）；流式期间的
 * 增量/结束/错误通过 chat:delta / chat:done / chat:error 事件推送。
 */
export function SendMessage(sessionID: string, text: string, effort: string): $CancellablePromise<void> {
    return $Call.ByID(1063940756, sessionID, text, effort);
}
