// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatDeltaEvent 在流式输出期间逐段推送。
 */
export interface ChatDeltaEvent {
    "sessionId": string;
    "delta": string;
}

/**
 * ChatDoneEvent 在整条回复结束时推送。
 */
export interface ChatDoneEvent {
    "sessionId": string;
    "content": string;
}

/**
 * ChatErrorEvent 在流式过程出错时推送。
 */
export interface ChatErrorEvent {
    "sessionId": string;
    "error": string;
}

/**
 * MessageDTO 是对前端暴露的单条消息。
 */
export interface MessageDTO {
    "id": number;
    "role": string;
    "content": string;
    "createdMs": number;
}

/**
 * SessionDTO 是对前端暴露的会话摘要。
 */
export interface SessionDTO {
    "id": string;
    "title": string;
    "createdAtMs": number;
    "updatedAtMs": number;
}
