// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Provider 描述一个 OpenAI-compatible 后端。
 */
export interface Provider {
    /**
     * 唯一标识，如 "openrouter"、"deepseek"、"ollama"
     */
    "ID": string;

    /**
     * 展示名
     */
    "Label": string;

    /**
     * 如 "https://openrouter.ai/api/v1"
     */
    "BaseURL": string;
    "APIKey": string;
}

/**
 * Settings 是应用设置。
 */
export interface Settings {
    "providers": Provider[] | null;
    "activeProviderId": string;
    "activeModel": string;
    "systemPrompt": string;
}
