// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Appearance 是界面外观设置。
 */
export interface Appearance {
    /**
     * light | dark | system
     */
    "theme": string;

    /**
     * 基础字号 px（0 表示默认 14）
     */
    "fontSize": number;

    /**
     * 暗色主题下 mermaid 图背景色(hex)，空=默认
     */
    "chartBg": string;
}

/**
 * Provider 描述一个 OpenAI-compatible 后端。
 */
export interface Provider {
    /**
     * 唯一标识，如 "openrouter"、"deepseek"、"ollama"
     */
    "ID": string;

    /**
     * 展示名
     */
    "Label": string;

    /**
     * 如 "https://openrouter.ai/api/v1"
     */
    "BaseURL": string;
    "APIKey": string;
}

/**
 * Settings 是应用设置。
 */
export interface Settings {
    "providers": Provider[] | null;
    "activeProviderId": string;
    "activeModel": string;
    "systemPrompt": string;
    "appearance": Appearance;
}
