// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Appearance 是界面外观设置。
 */
export interface Appearance {
    /**
     * light | dark | system
     */
    "theme": string;

    /**
     * 基础字号 px（0 表示默认 14）
     */
    "fontSize": number;

    /**
     * 暗色主题下 mermaid 图背景色(hex)，空=默认
     */
    "chartBg": string;
}

/**
 * MCPServer 描述一个 MCP（Model Context Protocol）服务器。
 * 传输固定为 Streamable HTTP（JSON-RPC 2.0 over POST）。
 */
export interface MCPServer {
    /**
     * 唯一标识；暴露给模型时工具名形如 "serverID_tool"
     */
    "id": string;

    /**
     * 展示名，如 "DeepWiki"
     */
    "label": string;

    /**
     * 如 "https://mcp.deepwiki.com/mcp"
     */
    "endpoint": string;

    /**
     * APIKey 可选：非空时以 "Authorization: Bearer <key>" 发送（无鉴权留空）。
     */
    "apiKey"?: string;
}

/**
 * Provider 描述一个 OpenAI-compatible 后端。
 */
export interface Provider {
    /**
     * 唯一标识，如 "openrouter"、"deepseek"、"ollama"
     */
    "ID": string;

    /**
     * 展示名
     */
    "Label": string;

    /**
     * 如 "https://openrouter.ai/api/v1"
     */
    "BaseURL": string;
    "APIKey": string;

    /**
     * 该提供商常用的模型（切换为该提供商时自动恢复）
     */
    "Model": string;

    /**
     * 扫描得到的可用模型列表（可选）
     */
    "Models": string[] | null;
}

/**
 * Settings 是应用设置。
 */
export interface Settings {
    "providers": Provider[] | null;
    "activeProviderId": string;
    "activeModel": string;
    "systemPrompt": string;
    "appearance": Appearance;
    "mcpServers"?: MCPServer[] | null;
}
